### ISSUE TITLE
오타가 있는 것 같아요

### ISSUE THREAD

**Issue by ryul99** [whywhyy/whywhyy#1]
안녕하세요! 오랜만이예요!! 잘 지내시나요??ㅎㅎ
앞으로 하고 싶은 것에 `Kotlin(금율결제원서버 구축 후 앱제작)` 이라구 되어 있는데 `금융결제원` 인 것 같아서 이슈 남겨요..!ㅎㅎ
항상 깃헙 너머로 소식 듣고 있어요ㅎㅎㅎ

**Comment by whywhyy** [comment]
창민쌤 !! 잘 지내시죠 !?오랜만이에요
저도 깃헙을 통해 소식 듣고있습니다. 😆

 오타 찾아주셔서 감사해요!!
